export default {
  settings: "Settings",
  endpoint: "Backend Endpoint (.env)",
  default_language: "Default Language",
  authorization: "Authorization Enable",
  auth_description: "Admin account will be generated by enabling this option",
  disabled: "Disabled",
  enabled: "Enabled",
};
